name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify NPM token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "❌ NPM_TOKEN secret is not set"
            exit 1
          else
            echo "✅ NPM_TOKEN secret is configured"
          fi

      - name: Install dependencies
        run: |
          cd packages/nodex-ts
          npm install

      - name: Run tests (opcional)
        run: |
          cd packages/nodex-ts
          npm test
        continue-on-error: true

      - name: Publish to npm
        run: |
          cd packages/nodex-ts
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
