name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    # Configurar environment si lo usaste en npm
    environment: npm

    permissions:
      contents: read
      id-token: write # Necesario para trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd packages/nodex-ts
          npm install

      - name: Run tests (opcional)
        run: |
          cd packages/nodex-ts
          npm test
        continue-on-error: true

      - name: Publish to npm
        run: |
          cd packages/nodex-ts
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
